import numpy as np
import pandas as pd
from numpy.random import randn

np.random.seed(101)

df = pd.DataFrame(randn(5,4), ['A','B','C','D','E'],['W','X','Y','Z'])
print("df: ")
print(df)
print("--------------------------------------")
print("df['W']")
print(df['W'])
print("type(df['W'])")
print(type(df['W']))
print("--------------------------------------")
print("df.W")
print(df.W)
print("--------------------------------------")
print("df[['W','Z']]")
print(df[['W','Z']])
print("--------------------------------------")
print("df['new'] = df['W'] + df['Y']")
df['new'] = df['W'] + df['Y']
print(df['new'])
print("df: ")
print(df)
print("--------------------------------------")
print("df.drop('new',axis=1)")
print(df.drop('new',axis=1))
df.drop('new',axis=1)
print(df)
print("--------------------------------------")
print("df.drop('new',axis=1),inplace=True")
df.drop('new',axis=1,inplace=True)
print(df)
print("--------------------------------------")
print("df.drop('E')")
print(df.drop('E'))
#df.drop('E',axis=1)
print(df)
print("--------------------------------------")
print("df.shape:")
print(df.shape)

print("--------------------------------------")
print("df.loc['A']")
print(df.loc['A'])
print("--------------------------------------")
print("df.iloc[2]")
print(df.iloc[2])
print("--------------------------------------")

print("--------------------------------------")
print("df.loc['B','Y']")
print(df.loc['B','Y'])

print("--------------------------------------")
print("df.loc[['A','B'],['W','Y']")
print(df.loc[['A','B'],['W','Y']])

